import type { AIImageImprovementProvider, AIImprovementRequest, AIImprovementResult } from "@/lib/product/providers/aiImageImprovementProvider"

/**
 * remove.bg provider - concrete implementation of AIImageImprovementProvider.
 *
 * WHY THIS PROVIDER: remove.bg performs SEGMENTATION-based
 * background removal - it isolates existing foreground pixels via
 * an alpha matte rather than regenerating any part of the image
 * through a diffusion model. This is a meaningfully stronger
 * technical guarantee for the load-bearing product-preservation
 * contract than a generative edit model, where even masked edits
 * carry a real risk of subtly regenerating pixels outside the
 * intended region. The real product pixels are never regenerated by
 * this provider - only the surrounding background pixels are
 * affected.
 *
 * Endpoint per official documentation (www.remove.bg/api, fetched
 * directly during this slice): POST https://api.remove.bg/v1.0/removebg,
 * authenticated via X-Api-Key header, multipart form with image_url
 * + size parameter. Supports PNG output with genuine alpha-channel
 * transparency.
 *
 * CREDENTIAL SAFETY: the API key is read only from
 * process.env.REMOVEBG_API_KEY (server-side only) and is never
 * included in any returned metadata, log statement, or error
 * message.
 */
export class RemoveBgProvider implements AIImageImprovementProvider {
  private readonly apiKey: string | undefined

  constructor(apiKey?: string) {
    this.apiKey = apiKey ?? process.env.REMOVEBG_API_KEY
  }

  async improve(request: AIImprovementRequest): Promise<AIImprovementResult> {
    if (request.operation !== "BACKGROUND_REMOVAL") {
      return {
        success: false,
        imageBytes: null,
        outputMimeType: null,
        providerMetadata: null,
        error: "This provider only supports background removal in this slice.",
      }
    }

    if (!this.apiKey) {
      return {
        success: false,
        imageBytes: null,
        outputMimeType: null,
        providerMetadata: null,
        error: "AI image improvement is not currently configured.",
      }
    }

    const formData = new FormData()
    formData.append("image_url", request.sourceImageUrl)
    formData.append("size", "auto")
    formData.append("format", "png")

    let response: Response
    try {
      response = await fetch("https://api.remove.bg/v1.0/removebg", {
        method: "POST",
        headers: { "X-Api-Key": this.apiKey },
        body: formData,
      })
    } catch {
      return {
        success: false,
        imageBytes: null,
        outputMimeType: null,
        providerMetadata: null,
        error: "Could not reach the image improvement service. Please try again.",
      }
    }

    if (!response.ok) {
      let safeMessage = "The image improvement service could not process this image."
      if (response.status === 429) {
        safeMessage = "The image improvement service is temporarily busy. Please try again shortly."
      } else if (response.status === 400) {
        safeMessage = "This image could not be processed - it may need a clearer product image."
      } else if (response.status === 401 || response.status === 403) {
        safeMessage = "AI image improvement is not currently available."
      }
      return {
        success: false,
        imageBytes: null,
        outputMimeType: null,
        providerMetadata: null,
        error: safeMessage,
      }
    }

    let imageBytes: ArrayBuffer
    try {
      imageBytes = await response.arrayBuffer()
    } catch {
      return {
        success: false,
        imageBytes: null,
        outputMimeType: null,
        providerMetadata: null,
        error: "Received an unreadable response from the image improvement service.",
      }
    }

    if (imageBytes.byteLength === 0) {
      return {
        success: false,
        imageBytes: null,
        outputMimeType: null,
        providerMetadata: null,
        error: "The image improvement service returned an empty result.",
      }
    }

    const requestId = response.headers.get("X-Request-Id")

    return {
      success: true,
      imageBytes,
      outputMimeType: "image/png",
      providerMetadata: {
        provider: "remove.bg",
        operation: "BACKGROUND_REMOVAL",
        providerRequestId: requestId,
        estimatedCostUsd: null,
      },
      error: null,
    }
  }
}
